# Generated by Django 6.0.5 on 2026-05-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor/a'), ('SELLER', 'Vendedor/a')], default='SELLER', max_length=20, verbose_name='rol'),
        ),
    ]
