# Generated by Django 6.0.5 on 2026-05-11 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor asignado a este vendedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores_asignados', to=settings.AUTH_USER_MODEL, verbose_name='supervisor/a asignado/a'),
        ),
    ]
