# Generated by Django 6.0.5 on 2026-05-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_supervisor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='crm_user',
        ),
    ]
