# Generated by Django 6.0.5 on 2026-05-07 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nif_nie', models.IntegerField()),
                ('adress', models.CharField(max_length=150, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(verbose_name='Telefono')),
                ('customer_code', models.CharField(max_length=50, verbose_name='Codigo Cliente')),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Casado'), ('SINGLE', 'Soltero')], default='SINGLE', max_length=20, verbose_name='Estado Civil')),
                ('profession', models.CharField(max_length=100, verbose_name='Profesión')),
                ('company', models.CharField(max_length=150, verbose_name='Empresa')),
                ('CIF', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('NEW_LEAD', 'Nuevo Lead'), ('INTERESTED', 'Interesado'), ('NEGOTIATION', 'Negociación'), ('ACTIVE', 'Activo')], default='NEW_LEAD', max_length=20, verbose_name='Estado')),
                ('product', models.CharField(choices=[('ALARMS_OUT', 'Alarmas exteriores'), ('ALARMS_IN', 'Alarmas interiores'), ('VIDEO_SUR', 'Video vigilancia'), ('MOTION_DET', 'Detector de Movimientos'), ('FULL_PACK', 'Paquete completo')], default='ALARMS_OUT', max_length=50, verbose_name='Productos')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Fecha de entrada')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor_Asignado')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_number', models.PositiveIntegerField(help_text='Ej: 1, 2, 3...')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(verbose_name='Detalle de la interacción')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['interaction_number'],
            },
        ),
    ]
