# Generated by Django 6.0.5 on 2026-05-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_number',
            field=models.PositiveIntegerField(help_text='Ej: 1, 2, 3...', verbose_name='Numero interacciones'),
        ),
    ]
