# Generated by Django 6.0.5 on 2026-05-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nif_nie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
