# Generated by Django 6.0.5 on 2026-05-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_nif_nie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa'),
        ),
    ]
