# Generated by Django 6.0.5 on 2026-05-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('NEW_LEAD', 'Nuevo Lead'), ('INTERESTED', 'Interesado'), ('NEGOTIATION', 'Negociación'), ('WIN', 'Activo')], default='NEW_LEAD', max_length=20, verbose_name='Estado'),
        ),
    ]
