# Generated by Django 6.0.5 on 2026-05-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'Casado/a'), ('SINGLE', 'Soltero/a')], default='SINGLE', max_length=20, verbose_name='Estado Civil'),
        ),
    ]
