# Generated by Django 6.0.5 on 2026-05-12 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_marital_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='interaction_number',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='note',
        ),
        migrations.AddField(
            model_name='interaction',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('CALL', 'Llamada Telefónica'), ('EMAIL', 'Correo Electrónico'), ('MEETING', 'Reunión Presencial'), ('WHATSAPP', 'Mensaje WhatsApp'), ('-', 'Default')], default='CALL', max_length=20),
        ),
        migrations.AddField(
            model_name='interaction',
            name='notes',
            field=models.TextField(default='Sin notas', help_text='Resumen de lo hablado'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
