# Generated by Django 6.0.5 on 2026-05-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_interaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('CALL', 'Llamada Telefónica'), ('EMAIL', 'Correo Electrónico'), ('MEETING', 'Reunión Presencial'), ('WHATSAPP', 'Mensaje WhatsApp'), ('VIDEOCALL', 'Videollamada'), ('-', 'Default')], default='CALL', max_length=20),
        ),
    ]
