# Generated by Django 6.0.5 on 2026-05-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_interaction_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nif_nie',
            field=models.CharField(blank=True, null=True),
        ),
    ]
