# Generated by Django 6.0.5 on 2026-05-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_nif_nie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('CALL', 'Llamada Telefónica'), ('EMAIL', 'Correo Electrónico'), ('MEETING', 'Reunión Presencial'), ('WHATSAPP', 'Mensaje WhatsApp'), ('VIDEOCALL', 'Videollamada'), ('-', 'Default')], default='CALL', max_length=20, verbose_name='Interacción'),
        ),
    ]
