# Generated by Django 6.0.5 on 2026-05-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_interaction_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Duaración'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='notes',
            field=models.TextField(default='Sin notas', help_text='Resumen de lo hablado', verbose_name='Notas'),
        ),
    ]
