# Generated by Django 6.0.5 on 2026-05-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_interaction_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CIF',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sector',
        ),
    ]
