# Generated by Django 6.0.5 on 2026-05-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_cif_remove_customer_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('Casado/a', 'Married'), ('Soltero/a', 'Single')], default='Soltero/a', max_length=20, verbose_name='Estado Civil'),
        ),
    ]
