# Generated by Django 6.0.5 on 2026-05-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_customer_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('Casado/a', 'Casado'), ('Soltero/a', 'Soltero')], default='Soltero/a', max_length=20, verbose_name='Estado Civil'),
        ),
    ]
