# Generated by Django 6.0.5 on 2026-05-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('Casado/a', 'Casado/a'), ('Soltero/a', 'Soltero/a')], default='Soltero/a', max_length=20, verbose_name='Estado Civil'),
        ),
    ]
