# Generated by Django 6.0.5 on 2026-05-27 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0017_alter_customer_marital_status"),
    ]

    operations = []
